run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - bodyclose
    # - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - noctx
    - staticcheck
    - typecheck
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/ricoberger/script_exporter
