tls:
  active: false
  crt: server.crt
  key: server.key

basicAuth:
  active: false
  username: admin
  password: admin

scripts:
  - name: test
    script: ./examples/test.sh
  - name: ping
    script: ./examples/ping.sh
