apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "script-exporter.fullname" . }}
  labels:
    {{- include "script-exporter.labels" . | nindent 4 }}
data:
  scripts.yaml: |
{{ tpl .Values.config . | indent 4 }}

{{- with .Values.scripts }}
{{- toYaml . | nindent 2 }}
{{- end }}
